version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./Nginx_Mosq/mosquitto/config:/mosquitto/config
      - ./Nginx_Mosq/mosquitto/data:/mosquitto/data
      - ./Nginx_Mosq/mosquitto/passwd:/etc/mosquitto/passwd
      - ./Nginx_Mosq/mosquitto/mosquitto.acl:/etc/mosquitto/mosquitto.acl
      - ./logs/mosquitto/:/mosquitto/log/
    networks:
      mosquitto-net:
        ipv4_address: 192.168.220.2

  proxy:
    container_name: proxy
    image: nginx:stable
    restart: always
    ports:
      - "9090:9090"
      - "443:443"
    volumes:
      - ./Nginx_Mosq/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/Nginx:/var/log/nginx
    networks:
      mosquitto-net:
        ipv4_address: 192.168.220.3

  http_server:
    build: ServerIoT/
    container_name: http_server
    depends_on:
      - mosquitto
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server_volume/server1.log:/app/server.log
    networks:
      mosquitto-net:
        ipv4_address: 192.168.220.4

networks:
  mosquitto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24

